### PR TITLE
fix: fail initialization when oci sdk auth is missing

### LINKED ISSUE #322: When walled OCID is configured, the app should fail on startup with a proper error message.
### Expected Behavior

Starting application should fail with a proper error when authentication credentials are not found and walled OCID is provided by configuration.

### Actual Behaviour

The application tries a fallback mechanism without proper error displayed in the info logger level.

Example of stack trace from the info log:

```
Task :compileJava UP-TO-DATE
Task :processResources UP-TO-DATE
Task :classes UP-TO-DATE

> Task :run
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.2.4)

[36m16:35:38.871[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Established active environments: [oraclecloud]
[36m16:35:40.341[0;39m [1;30m[main][0;39m [1;31mERROR[0;39m [35mio.micronaut.runtime.Micronaut[0;39m - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]

Message: Error configuring data source 'default'. No URL specified
Path Taken: DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]

Message: Error configuring data source 'default'. No URL specified
Path Taken: DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1938)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:237)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3453)
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3883)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:329)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:183)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:313)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at my.app.Application.main(Application.java:8)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [javax.sql.DataSource]

Message: Error configuring data source 'default'. No URL specified
Path Taken: DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2363)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2820)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2782)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1638)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1933)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1189)
	at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0$Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:136)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2653)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1932)
	... 9 common frames omitted
Caused by: io.micronaut.context.exceptions.ConfigurationException: Error configuring data source 'default'. No URL specified
	at io.micronaut.jdbc.CalculatedSettings.getUrl(CalculatedSettings.java:109)
	at io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration.getUrl(DatasourceConfiguration.java:96)
	at io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration.postConstruct(DatasourceConfiguration.java:68)
	at io.micronaut.configuration.jdbc.hikari.$DatasourceConfiguration$Definition.initialize(Unknown Source)
	at io.micronaut.configuration.jdbc.hikari.$DatasourceConfiguration$Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinition.build(AbstractInitializableBeanDefinition.java:707)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:132)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
	... 23 common frames omitted

> Task :run FAILED
3 actionable tasks: 1 executed, 2 up-to-date
```

Example of stack trace from the debug log:

```> Task :compileJava UP-TO-DATE
> Task :processResources
> Task :classes

> Task :run
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.2.4)

[36m15:44:12.222[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.core.optim.StaticOptimizations[0;39m - No optimizations class io.micronaut.core.reflect.ClassUtils$Optimizations found
[36m15:44:12.236[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.core.optim.StaticOptimizations[0;39m - No optimizations class io.micronaut.core.util.EnvironmentProperties found
[36m15:44:12.248[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.core.optim.StaticOptimizations[0;39m - No optimizations class io.micronaut.context.env.ConstantPropertySources found
[36m15:44:12.262[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.core.optim.StaticOptimizations[0;39m - No optimizations class io.micronaut.core.io.service.SoftServiceLoader$Optimizations found
[36m15:44:32.234[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.io.service.SoftServiceLoader[0;39m - Loaded 582 services of type io.micronaut.inject.BeanDefinitionReference
[36m15:44:32.235[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.io.service.SoftServiceLoader[0;39m - Loading io.micronaut.inject.BeanDefinitionReference services took 19966ms
[36m15:44:32.245[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Environment deduction is using the default of: true
[36m15:44:32.263[0;39m [1;30m[main][0;39m [34mINFO [0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Established active environments: [oraclecloud]
[36m15:44:32.269[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Starting environment io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@6d3a388c for active names [oraclecloud]
[36m15:44:32.328[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.io.service.SoftServiceLoader[0;39m - Loaded 6 services of type io.micronaut.context.env.PropertySourceLoader
[36m15:44:32.328[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.io.service.SoftServiceLoader[0;39m - Loading io.micronaut.context.env.PropertySourceLoader services took 58ms
[36m15:44:32.328[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Reading property sources from loader: io.micronaut.jackson.core.env.JsonPropertySourceLoader@57af006c
[36m15:44:32.329[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.e.AbstractPropertySourceLoader[0;39m - No PropertySource found for file name: application.json
[36m15:44:32.335[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.e.AbstractPropertySourceLoader[0;39m - No PropertySource found for file name: application-oraclecloud.json
[36m15:44:32.336[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Reading property sources from loader: io.micronaut.jackson.core.env.EnvJsonPropertySourceLoader@69997e9d
[36m15:44:32.337[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.e.AbstractPropertySourceLoader[0;39m - No PropertySource found for file name: application.json
[36m15:44:32.337[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.e.AbstractPropertySourceLoader[0;39m - No PropertySource found for file name: application-oraclecloud.json
[36m15:44:32.338[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Reading property sources from loader: io.micronaut.jackson.core.env.CloudFoundryVcapApplicationPropertySourceLoader@793be5ca
[36m15:44:32.338[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.e.AbstractPropertySourceLoader[0;39m - No PropertySource found for file name: application.VCAP_APPLICATION
[36m15:44:32.339[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.e.AbstractPropertySourceLoader[0;39m - No PropertySource found for file name: application-oraclecloud.VCAP_APPLICATION
[36m15:44:32.339[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Reading property sources from loader: io.micronaut.jackson.core.env.CloudFoundryVcapServicesPropertySourceLoader@2df9b86
[36m15:44:32.339[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.e.AbstractPropertySourceLoader[0;39m - No PropertySource found for file name: application.VCAP_SERVICES
[36m15:44:32.340[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.e.AbstractPropertySourceLoader[0;39m - No PropertySource found for file name: application-oraclecloud.VCAP_SERVICES
[36m15:44:32.340[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Reading property sources from loader: io.micronaut.context.env.yaml.YamlPropertySourceLoader@37654521
[36m15:44:32.353[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.e.AbstractPropertySourceLoader[0;39m - Found PropertySource for file name: application.yml
[36m15:44:32.528[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.e.AbstractPropertySourceLoader[0;39m - Found PropertySource for file name: application-oraclecloud.yml
[36m15:44:32.533[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Reading property sources from loader: io.micronaut.context.env.PropertiesPropertySourceLoader@4d1c005e
[36m15:44:32.539[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.e.AbstractPropertySourceLoader[0;39m - No PropertySource found for file name: application.properties
[36m15:44:32.541[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.e.AbstractPropertySourceLoader[0;39m - No PropertySource found for file name: application-oraclecloud.properties
[36m15:44:32.546[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Processing property source: application
[36m15:44:32.549[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Processing property source: application-oraclecloud
[36m15:44:32.550[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Processing property source: env
[36m15:44:32.562[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.env.DefaultEnvironment[0;39m - Processing property source: system
[36m15:44:32.577[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: Environment
[36m15:44:32.579[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - No bean candidates found for type: Environment
[36m15:44:32.617[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Starting BeanContext
[36m15:44:32.679[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.io.service.SoftServiceLoader[0;39m - Loaded 6 services of type io.micronaut.inject.BeanConfiguration
[36m15:44:32.698[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.c.io.service.SoftServiceLoader[0;39m - Loading io.micronaut.inject.BeanConfiguration services took 75ms
[36m15:44:32.787[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Configuration: io.micronaut.http.server.cors will not be loaded due to failing conditions:
[36m15:44:32.788[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Required property [micronaut.server.cors.enabled] with value [true] not present
[36m15:44:32.814[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: HttpClientRegistry
[36m15:44:32.915[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry] for type: HttpClientRegistry
[36m15:44:32.915[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry]
[36m15:44:32.941[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: BeanCreatedEventListener
[36m15:44:32.977[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.flyway.$GormMigrationRunner$Definition$Intercepted$Definition] will not be loaded due to failing conditions:
[36m15:44:32.977[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [org.grails.orm.hibernate.HibernateDatastore] is not present
[36m15:44:32.980[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.flyway.$GormMigrationRunner$Definition] will not be loaded due to failing conditions:
[36m15:44:32.981[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [org.grails.orm.hibernate.HibernateDatastore] is not present
[36m15:44:32.982[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.oraclecloud.atp.jdbc.upc.$UcpPoolConfigurationListener$Definition] will not be loaded due to failing conditions:
[36m15:44:32.982[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [oracle.ucp.jdbc.PoolDataSource] is not present
[36m15:44:32.983[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.jdbc.spring.$DataSourceTransactionManagerFactory$TransactionAwareDataSourceListener1$Definition] will not be loaded due to failing conditions:
[36m15:44:32.983[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [org.springframework.jdbc.datasource.DataSourceTransactionManager] is not present
[36m15:44:32.985[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: DataSourceTransactionManagerFactory
[36m15:44:32.986[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.jdbc.spring.$DataSourceTransactionManagerFactory$Definition] will not be loaded due to failing conditions:
[36m15:44:32.987[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [org.springframework.jdbc.datasource.DataSourceTransactionManager] is not present
[36m15:44:32.989[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [] for type: DataSourceTransactionManagerFactory
[36m15:44:32.990[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.web.router.version.$VersionAwareRouterListener$Definition] will not be loaded due to failing conditions:
[36m15:44:32.991[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Required property [micronaut.router.versioning.enabled] with value [true] not present
[36m15:44:32.992[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.flyway.$AlternativeMigrationRunner$Definition$Intercepted, Definition: io.micronaut.flyway.$DataSourceMigrationRunner$Definition$Intercepted, Definition: io.micronaut.http.server.netty.binders.NettyBinderRegistrar, Definition: io.micronaut.scheduling.instrument.ExecutorServiceInstrumenter, Definition: io.micronaut.transaction.jdbc.TransactionAwareDataSource] for type: BeanCreatedEventListener
[36m15:44:32.993[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.flyway.$AlternativeMigrationRunner$Definition$Intercepted, Definition: io.micronaut.flyway.$DataSourceMigrationRunner$Definition$Intercepted, Definition: io.micronaut.http.server.netty.binders.NettyBinderRegistrar, Definition: io.micronaut.scheduling.instrument.ExecutorServiceInstrumenter, Definition: io.micronaut.transaction.jdbc.TransactionAwareDataSource]
[36m15:44:33.040[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: ApplicationEventPublisher eventPublisher
[36m15:44:33.043[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [io.micronaut.context.event.ApplicationEventPublisherFactory@1c927e1b] for type: ApplicationEventPublisher eventPublisher
[36m15:44:33.049[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [io.micronaut.context.event.ApplicationEventPublisherFactory@1c927e1b]
[36m15:44:33.055[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [io.micronaut.context.event.ApplicationEventPublisherFactory@1c927e1b] for type: eventPublisher 
[36m15:44:33.058[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.context.event.ApplicationEventPublisherFactory$1@2438dcd] from definition [io.micronaut.context.event.ApplicationEventPublisherFactory@1c927e1b] with qualifier [null]
[36m15:44:33.072[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolving beans for type: @InterceptorBinding(io.micronaut.scheduling.annotation.Async)@InterceptorBinding(interceptorType = class io.micronaut.scheduling.async.AsyncInterceptor) io.micronaut.aop.Interceptor 
[36m15:44:33.078[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: Interceptor T
[36m15:44:33.101[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.transaction.jdbc.TransactionalConnectionInterceptor, Definition: io.micronaut.transaction.interceptor.TransactionalEventInterceptor, Definition: io.micronaut.runtime.context.scope.refresh.RefreshInterceptor, Definition: io.micronaut.scheduling.async.AsyncInterceptor, Definition: io.micronaut.data.intercept.DataIntroductionAdvice, Definition: io.micronaut.websocket.interceptor.ClientWebSocketInterceptor, Definition: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice, Definition: io.micronaut.retry.intercept.RecoveryInterceptor, Definition: io.micronaut.transaction.interceptor.TransactionalInterceptor, Definition: io.micronaut.retry.intercept.DefaultRetryInterceptor, Definition: io.micronaut.runtime.context.env.ConfigurationIntroductionAdvice, Definition: io.micronaut.validation.ValidatingInterceptor] for type: Interceptor T
[36m15:44:33.103[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.transaction.jdbc.TransactionalConnectionInterceptor, Definition: io.micronaut.transaction.interceptor.TransactionalEventInterceptor, Definition: io.micronaut.runtime.context.scope.refresh.RefreshInterceptor, Definition: io.micronaut.scheduling.async.AsyncInterceptor, Definition: io.micronaut.data.intercept.DataIntroductionAdvice, Definition: io.micronaut.websocket.interceptor.ClientWebSocketInterceptor, Definition: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice, Definition: io.micronaut.retry.intercept.RecoveryInterceptor, Definition: io.micronaut.transaction.interceptor.TransactionalInterceptor, Definition: io.micronaut.retry.intercept.DefaultRetryInterceptor, Definition: io.micronaut.runtime.context.env.ConfigurationIntroductionAdvice, Definition: io.micronaut.validation.ValidatingInterceptor]
[36m15:44:33.105[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Qualifying bean [T] from candidates [Definition: io.micronaut.transaction.jdbc.TransactionalConnectionInterceptor, Definition: io.micronaut.transaction.interceptor.TransactionalEventInterceptor, Definition: io.micronaut.runtime.context.scope.refresh.RefreshInterceptor, Definition: io.micronaut.scheduling.async.AsyncInterceptor, Definition: io.micronaut.data.intercept.DataIntroductionAdvice, Definition: io.micronaut.websocket.interceptor.ClientWebSocketInterceptor, Definition: io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice, Definition: io.micronaut.retry.intercept.RecoveryInterceptor, Definition: io.micronaut.transaction.interceptor.TransactionalInterceptor, Definition: io.micronaut.retry.intercept.DefaultRetryInterceptor, Definition: io.micronaut.runtime.context.env.ConfigurationIntroductionAdvice, Definition: io.micronaut.validation.ValidatingInterceptor] for qualifier: @InterceptorBinding(io.micronaut.scheduling.annotation.Async)@InterceptorBinding(interceptorType = class io.micronaut.scheduling.async.AsyncInterceptor) 
[36m15:44:33.113[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: BeanProvider T
[36m15:44:33.113[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: BeanProvider T
[36m15:44:33.113[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee]
[36m15:44:33.116[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Qualifying bean [T] for qualifier: @Named('scheduled') 
[36m15:44:33.126[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: @Named('scheduled') T 
[36m15:44:33.127[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: ExecutorService T
[36m15:44:33.133[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.netty.channel.DefaultEventLoopGroupRegistry, Definition: io.micronaut.scheduling.executor.ExecutorFactory] for type: ExecutorService T
[36m15:44:33.134[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: EventLoopGroupConfiguration
[36m15:44:33.137[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration$Worker, Definition: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration$Parent, Definition: io.micronaut.http.netty.channel.DefaultEventLoopGroupConfiguration] for type: EventLoopGroupConfiguration
[36m15:44:33.145[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration$Worker, Definition: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration$Parent]
[36m15:44:33.252[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: ExecutorConfiguration
[36m15:44:33.259[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.scheduling.executor.$IOExecutorServiceConfig$Configuration0$Definition] will not be loaded due to failing conditions:
[36m15:44:33.259[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Property [micronaut.executors.io] present
[36m15:44:33.267[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.scheduling.executor.ScheduledExecutorServiceConfig, Definition: io.micronaut.scheduling.executor.UserExecutorConfiguration] for type: ExecutorConfiguration
[36m15:44:33.270[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.scheduling.executor.ScheduledExecutorServiceConfig, Definition: io.micronaut.scheduling.executor.UserExecutorConfiguration]
[36m15:44:33.275[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.scheduling.executor.ExecutorFactory, Definition: io.micronaut.scheduling.executor.ExecutorFactory]
[36m15:44:33.281[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.inject.provider.BeanProviderDefinition$1@3eb91815] from definition [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] with qualifier [@Named('scheduled')]
[36m15:44:33.281[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.scheduling.async.AsyncInterceptor@56dc1551] from definition [Definition: io.micronaut.scheduling.async.AsyncInterceptor] with qualifier [@InterceptorBinding(io.micronaut.scheduling.annotation.Async)@InterceptorBinding(interceptorType = class io.micronaut.scheduling.async.AsyncInterceptor)]
[36m15:44:33.283[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.scheduling.async.AsyncInterceptor@56dc1551 for type [@InterceptorBinding(io.micronaut.scheduling.annotation.Async)@InterceptorBinding(interceptorType = class io.micronaut.scheduling.async.AsyncInterceptor) T] using bean key @InterceptorBinding(io.micronaut.scheduling.annotation.Async)@InterceptorBinding(interceptorType = class io.micronaut.scheduling.async.AsyncInterceptor) AsyncInterceptor
[36m15:44:33.291[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found 1 beans for type [@InterceptorBinding(io.micronaut.scheduling.annotation.Async)@InterceptorBinding(interceptorType = class io.micronaut.scheduling.async.AsyncInterceptor) T]: [BeanRegistration: io.micronaut.scheduling.async.AsyncInterceptor@56dc1551] 
[36m15:44:33.299[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: InterceptorRegistry
[36m15:44:33.302[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [io.micronaut.aop.internal.InterceptorRegistryBean@48b67364] for type: InterceptorRegistry
[36m15:44:33.302[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [io.micronaut.aop.internal.InterceptorRegistryBean@48b67364]
[36m15:44:33.302[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [io.micronaut.aop.internal.InterceptorRegistryBean@48b67364] for type: InterceptorRegistry 
[36m15:44:33.306[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.aop.chain.DefaultInterceptorRegistry@72ef8d15] from definition [io.micronaut.aop.internal.InterceptorRegistryBean@48b67364] with qualifier [null]
[36m15:44:33.307[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.aop.chain.DefaultInterceptorRegistry@72ef8d15 for type [InterceptorRegistry] using bean key InterceptorRegistry
[36m15:44:33.320[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.flyway.$AlternativeMigrationRunner$Definition$Intercepted@3fa247d1] from definition [Definition: io.micronaut.flyway.$AlternativeMigrationRunner$Definition$Intercepted] with qualifier [null]
[36m15:44:33.321[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.flyway.$AlternativeMigrationRunner$Definition$Intercepted@3fa247d1 for type [$AlternativeMigrationRunner$Definition$Intercepted] using bean key $AlternativeMigrationRunner$Definition$Intercepted
[36m15:44:33.322[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.context.event.ApplicationEventPublisherFactory$1@2438dcd] from definition [io.micronaut.context.event.ApplicationEventPublisherFactory@1c927e1b] with qualifier [null]
[36m15:44:33.322[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: DataSourceResolver dataSourceResolver
[36m15:44:33.323[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.jdbc.spring.$SpringDataSourceResolver$Definition] will not be loaded due to failing conditions:
[36m15:44:33.323[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [org.springframework.jdbc.datasource.DelegatingDataSource] is not present
[36m15:44:33.323[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.core.reflect.ClassUtils[0;39m - Attempting to dynamically load class org.springframework.jdbc.datasource.DataSourceTransactionManager
[36m15:44:33.325[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.core.reflect.ClassUtils[0;39m - Class org.springframework.jdbc.datasource.DataSourceTransactionManager is not present
[36m15:44:33.326[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.core.reflect.ClassUtils[0;39m - Attempting to dynamically load class org.springframework.jdbc.datasource.DataSourceTransactionManager
[36m15:44:33.326[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.core.reflect.ClassUtils[0;39m - Class org.springframework.jdbc.datasource.DataSourceTransactionManager is not present
[36m15:44:33.328[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.transaction.jdbc.DelegatingDataSourceResolver] for type: DataSourceResolver dataSourceResolver
[36m15:44:33.329[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.transaction.jdbc.DelegatingDataSourceResolver]
[36m15:44:33.329[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.transaction.jdbc.DelegatingDataSourceResolver] for type: dataSourceResolver 
[36m15:44:33.370[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.transaction.jdbc.DelegatingDataSourceResolver@4e928fbf] from definition [Definition: io.micronaut.transaction.jdbc.DelegatingDataSourceResolver] with qualifier [null]
[36m15:44:33.370[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.transaction.jdbc.DelegatingDataSourceResolver@4e928fbf for type [DataSourceResolver] using bean key DelegatingDataSourceResolver
[36m15:44:33.371[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolving beans for type: @InterceptorBinding(io.micronaut.scheduling.annotation.Async)@InterceptorBinding(interceptorType = class io.micronaut.scheduling.async.AsyncInterceptor) io.micronaut.aop.Interceptor 
[36m15:44:33.371[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.aop.chain.DefaultInterceptorRegistry@72ef8d15] for type [InterceptorRegistry] and qualifier [null]
[36m15:44:33.372[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.flyway.$DataSourceMigrationRunner$Definition$Intercepted@2e32ccc5] from definition [Definition: io.micronaut.flyway.$DataSourceMigrationRunner$Definition$Intercepted] with qualifier [null]
[36m15:44:33.372[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.flyway.$DataSourceMigrationRunner$Definition$Intercepted@2e32ccc5 for type [$DataSourceMigrationRunner$Definition$Intercepted] using bean key $DataSourceMigrationRunner$Definition$Intercepted
[36m15:44:33.375[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: ConversionService conversionService
[36m15:44:33.392[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [io.micronaut.context.DefaultBeanContext$NoInjectionBeanDefinition@41c2284a] for type: ConversionService conversionService
[36m15:44:33.392[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [io.micronaut.context.DefaultBeanContext$NoInjectionBeanDefinition@41c2284a]
[36m15:44:33.393[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [io.micronaut.context.DefaultBeanContext$NoInjectionBeanDefinition@41c2284a] for type: conversionService 
[36m15:44:33.394[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@6d3a388c for type [conversionService] using bean key RuntimeConfiguredEnvironment
[36m15:44:33.394[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@6d3a388c] for type [ConversionService conversionService] and qualifier [null]
[36m15:44:33.394[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: HttpContentProcessorResolver httpContentProcessorResolver
[36m15:44:33.449[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.server.netty.DefaultHttpContentProcessorResolver] for type: HttpContentProcessorResolver httpContentProcessorResolver
[36m15:44:33.449[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.http.server.netty.DefaultHttpContentProcessorResolver]
[36m15:44:33.449[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.http.server.netty.DefaultHttpContentProcessorResolver] for type: httpContentProcessorResolver 
[36m15:44:33.450[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: BeanProvider serverConfiguration
[36m15:44:33.450[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: BeanProvider serverConfiguration
[36m15:44:33.450[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee]
[36m15:44:33.450[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: serverConfiguration 
[36m15:44:33.450[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: NettyHttpServerConfiguration T
[36m15:44:33.536[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration] for type: NettyHttpServerConfiguration T
[36m15:44:33.544[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration]
[36m15:44:33.545[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.inject.provider.BeanProviderDefinition$1@14a50707] from definition [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] with qualifier [null]
[36m15:44:33.545[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.http.server.netty.DefaultHttpContentProcessorResolver@4d518b32] from definition [Definition: io.micronaut.http.server.netty.DefaultHttpContentProcessorResolver] with qualifier [null]
[36m15:44:33.545[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.http.server.netty.DefaultHttpContentProcessorResolver@4d518b32 for type [HttpContentProcessorResolver] using bean key DefaultHttpContentProcessorResolver
[36m15:44:33.550[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: BeanProvider httpServerConfiguration
[36m15:44:33.551[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: BeanProvider httpServerConfiguration
[36m15:44:33.551[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee]
[36m15:44:33.551[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: httpServerConfiguration 
[36m15:44:33.551[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: HttpServerConfiguration T
[36m15:44:33.556[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Bean [class io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration] replaces existing bean of type [class io.micronaut.http.server.HttpServerConfiguration]
[36m15:44:33.558[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration] for type: HttpServerConfiguration T
[36m15:44:33.558[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration]
[36m15:44:33.558[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.inject.provider.BeanProviderDefinition$1@479cbee5] from definition [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] with qualifier [null]
[36m15:44:33.559[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: BeanProvider executorService
[36m15:44:33.559[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: BeanProvider executorService
[36m15:44:33.559[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee]
[36m15:44:33.559[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Qualifying bean [executorService] for qualifier: @Named('io') 
[36m15:44:33.559[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: @Named('io') executorService 
[36m15:44:33.559[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: ExecutorService T
[36m15:44:33.561[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.netty.channel.DefaultEventLoopGroupRegistry, Definition: io.micronaut.scheduling.executor.ExecutorFactory] for type: ExecutorService T
[36m15:44:33.561[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: EventLoopGroupConfiguration
[36m15:44:33.586[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration$Worker, Definition: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration$Parent, Definition: io.micronaut.http.netty.channel.DefaultEventLoopGroupConfiguration] for type: EventLoopGroupConfiguration
[36m15:44:33.592[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration$Worker, Definition: io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration$Parent]
[36m15:44:33.593[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: ExecutorConfiguration
[36m15:44:33.595[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.scheduling.executor.$IOExecutorServiceConfig$Configuration0$Definition] will not be loaded due to failing conditions:
[36m15:44:33.618[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Property [micronaut.executors.io] present
[36m15:44:33.619[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.scheduling.executor.ScheduledExecutorServiceConfig, Definition: io.micronaut.scheduling.executor.UserExecutorConfiguration] for type: ExecutorConfiguration
[36m15:44:33.622[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.scheduling.executor.ScheduledExecutorServiceConfig, Definition: io.micronaut.scheduling.executor.UserExecutorConfiguration]
[36m15:44:33.628[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.scheduling.executor.ExecutorFactory, Definition: io.micronaut.scheduling.executor.ExecutorFactory]
[36m15:44:33.632[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.inject.provider.BeanProviderDefinition$1@59e2d8e3] from definition [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] with qualifier [@Named('io')]
[36m15:44:33.633[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.http.server.netty.binders.NettyBinderRegistrar@2b72cb8a] from definition [Definition: io.micronaut.http.server.netty.binders.NettyBinderRegistrar] with qualifier [null]
[36m15:44:33.633[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.http.server.netty.binders.NettyBinderRegistrar@2b72cb8a for type [NettyBinderRegistrar] using bean key NettyBinderRegistrar
[36m15:44:33.666[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolving beans for type: io.micronaut.scheduling.instrument.InvocationInstrumenterFactory
[36m15:44:33.667[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: InvocationInstrumenterFactory E
[36m15:44:33.670[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.server.context.ServerRequestContextInstrumentation] for type: InvocationInstrumenterFactory E
[36m15:44:33.670[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.http.server.context.ServerRequestContextInstrumentation]
[36m15:44:33.671[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.http.server.context.ServerRequestContextInstrumentation@4bf48f6] from definition [Definition: io.micronaut.http.server.context.ServerRequestContextInstrumentation] with qualifier [null]
[36m15:44:33.671[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.http.server.context.ServerRequestContextInstrumentation@4bf48f6 for type [E] using bean key ServerRequestContextInstrumentation
[36m15:44:33.671[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found 1 beans for type [E]: [BeanRegistration: io.micronaut.http.server.context.ServerRequestContextInstrumentation@4bf48f6] 
[36m15:44:33.672[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.scheduling.instrument.ExecutorServiceInstrumenter@1c39680d] from definition [Definition: io.micronaut.scheduling.instrument.ExecutorServiceInstrumenter] with qualifier [null]
[36m15:44:33.673[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.scheduling.instrument.ExecutorServiceInstrumenter@1c39680d for type [ExecutorServiceInstrumenter] using bean key ExecutorServiceInstrumenter
[36m15:44:33.675[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.transaction.jdbc.TransactionAwareDataSource@1c852c0f] from definition [Definition: io.micronaut.transaction.jdbc.TransactionAwareDataSource] with qualifier [null]
[36m15:44:33.676[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.transaction.jdbc.TransactionAwareDataSource@1c852c0f for type [TransactionAwareDataSource] using bean key TransactionAwareDataSource
[36m15:44:33.676[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: BeanInitializedEventListener
[36m15:44:33.682[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: OracleWalletArchiveProvider
[36m15:44:33.683[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: DatabaseClient
[36m15:44:33.686[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: AbstractAuthenticationDetailsProvider
[36m15:44:33.688[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: InstancePrincipalConfiguration
[36m15:44:33.691[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.oraclecloud.core.$InstancePrincipalConfiguration$Definition] will not be loaded due to failing conditions:
[36m15:44:33.692[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Required property [oci.config.instance-principal.enabled] with value [true] not present
[36m15:44:33.694[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [] for type: InstancePrincipalConfiguration
[36m15:44:33.695[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [Definition: io.micronaut.oraclecloud.core.OracleCloudCoreFactory] will not be loaded due to failing conditions:
[36m15:44:33.695[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * No bean of type [class io.micronaut.oraclecloud.core.InstancePrincipalConfiguration] present within context
[36m15:44:33.698[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.oraclecloud.core.$OracleCloudCoreFactory$SimpleAuthenticationDetailsProvider1$Definition] will not be loaded due to failing conditions:
[36m15:44:33.699[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Required property [oci.tenant-id] with value [null] not present
[36m15:44:33.730[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [Definition: io.micronaut.oraclecloud.core.OracleCloudCoreFactory] will not be loaded due to failing conditions:
[36m15:44:33.730[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * No Oracle Cloud Configuration found at path: /Users/myuser/.oci/config
[36m15:44:33.730[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Custom condition [class io.micronaut.oraclecloud.core.OracleCloudConfigCondition] failed evaluation
[36m15:44:33.731[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.oraclecloud.core.$OracleCloudCoreFactory$ResourcePrincipalAuthenticationDetailsProvider2$Definition] will not be loaded due to failing conditions:
[36m15:44:33.731[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Required property [OCI_RESOURCE_PRINCIPAL_VERSION] with value [null] not present
[36m15:44:33.732[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [] for type: AbstractAuthenticationDetailsProvider
[36m15:44:33.732[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [Definition: io.micronaut.oraclecloud.clients.database.DatabaseClientFactory] will not be loaded due to failing conditions:
[36m15:44:33.732[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * No bean of type [interface com.oracle.bmc.auth.AbstractAuthenticationDetailsProvider] present within context
[36m15:44:33.736[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [] for type: DatabaseClient
[36m15:44:33.737[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [Definition: io.micronaut.oraclecloud.atp.jdbc.OracleWalletArchiveProvider] will not be loaded due to failing conditions:
[36m15:44:33.737[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * No bean of type [class com.oracle.bmc.database.DatabaseClient] present within context
[36m15:44:33.738[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [] for type: OracleWalletArchiveProvider
[36m15:44:33.738[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [Definition: io.micronaut.oraclecloud.atp.jdbc.hikari.HikariPoolConfigurationListener] will not be loaded due to failing conditions:
[36m15:44:33.738[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * No bean of type [class io.micronaut.oraclecloud.atp.jdbc.OracleWalletArchiveProvider] present within context
[36m15:44:33.738[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [] for type: BeanInitializedEventListener
[36m15:44:33.742[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolving beans for type: io.micronaut.core.convert.TypeConverter
[36m15:44:33.742[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: TypeConverter
[36m15:44:33.804[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.http.cookie.SameSiteConverter, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] for type: TypeConverter
[36m15:44:33.806[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.http.cookie.SameSiteConverter, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory]
[36m15:44:33.809[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: CustomScope
[36m15:44:34.032[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.runtime.http.scope.RequestCustomScope, Definition: io.micronaut.runtime.context.scope.refresh.RefreshScope, Definition: io.micronaut.runtime.context.scope.ThreadLocalCustomScope] for type: CustomScope
[36m15:44:34.032[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.runtime.http.scope.RequestCustomScope, Definition: io.micronaut.runtime.context.scope.refresh.RefreshScope, Definition: io.micronaut.runtime.context.scope.ThreadLocalCustomScope]
[36m15:44:34.032[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Qualifying bean [CustomScope] for qualifier: <io.micronaut.context.annotation.Prototype> 
[36m15:44:34.034[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - No qualifying beans of type [CustomScope] found for qualifier: <io.micronaut.context.annotation.Prototype> 
[36m15:44:34.042[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: OracleTypeConvertersFactory
[36m15:44:34.045[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] for type: OracleTypeConvertersFactory
[36m15:44:34.045[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory]
[36m15:44:34.045[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] for type: OracleTypeConvertersFactory 
[36m15:44:34.048[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory@6e01f9b0] from definition [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] with qualifier [null]
[36m15:44:34.048[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory@6e01f9b0 for type [OracleTypeConvertersFactory] using bean key OracleTypeConvertersFactory
[36m15:44:34.050[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$278/0x0000000840845840@421e361] from definition [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] with qualifier [null]
[36m15:44:34.053[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory@6e01f9b0] for type [OracleTypeConvertersFactory] and qualifier [null]
[36m15:44:34.054[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$279/0x0000000840845c40@389c4eb1] from definition [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] with qualifier [null]
[36m15:44:34.055[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.http.cookie.SameSiteConverter@34f6515b] from definition [Definition: io.micronaut.http.cookie.SameSiteConverter] with qualifier [null]
[36m15:44:34.055[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.http.cookie.SameSiteConverter@34f6515b for type [TypeConverter] using bean key SameSiteConverter
[36m15:44:34.055[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory@6e01f9b0] for type [OracleTypeConvertersFactory] and qualifier [null]
[36m15:44:34.056[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$280/0x0000000840846040@1187c9e8] from definition [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] with qualifier [null]
[36m15:44:34.056[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory@6e01f9b0] for type [OracleTypeConvertersFactory] and qualifier [null]
[36m15:44:34.057[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$281/0x0000000840846440@78a773fd] from definition [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] with qualifier [null]
[36m15:44:34.070[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory@6e01f9b0] for type [OracleTypeConvertersFactory] and qualifier [null]
[36m15:44:34.071[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$282/0x0000000840846840@16aa8654] from definition [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] with qualifier [null]
[36m15:44:34.071[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory@6e01f9b0] for type [OracleTypeConvertersFactory] and qualifier [null]
[36m15:44:34.073[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$283/0x0000000840846c40@45ac5f9b] from definition [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] with qualifier [null]
[36m15:44:34.073[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found 7 beans for type [TypeConverter]: [BeanRegistration: io.micronaut.http.cookie.SameSiteConverter@34f6515b, BeanRegistration: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$281/0x0000000840846440@78a773fd, BeanRegistration: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$280/0x0000000840846040@1187c9e8, BeanRegistration: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$282/0x0000000840846840@16aa8654, BeanRegistration: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$283/0x0000000840846c40@45ac5f9b, BeanRegistration: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$278/0x0000000840845840@421e361, BeanRegistration: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$279/0x0000000840845c40@389c4eb1] 
[36m15:44:34.074[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolving beans for type: io.micronaut.core.convert.TypeConverterRegistrar
[36m15:44:34.074[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: TypeConverterRegistrar
[36m15:44:34.107[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.reactor.convert.$ReactorToRxJava2ConverterRegistrar$Definition] will not be loaded due to failing conditions:
[36m15:44:34.108[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [io.reactivex.Maybe] is not present
[36m15:44:34.108[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.reactor.convert.$ReactorToRxJava3ConverterRegistrar$Definition] will not be loaded due to failing conditions:
[36m15:44:34.108[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [io.reactivex.rxjava3.core.Maybe] is not present
[36m15:44:34.141[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.http.netty.channel.converters.$KQueueChannelOptionFactory$Definition] will not be loaded due to failing conditions:
[36m15:44:34.141[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [io.netty.channel.kqueue.KQueue] is not present
[36m15:44:34.142[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.reactive.flow.converters.$FlowConverterRegistrar$Definition] will not be loaded due to failing conditions:
[36m15:44:34.142[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [kotlinx.coroutines.reactive.ReactiveFlowKt] is not present
[36m15:44:34.151[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.converters.HttpConverterRegistrar, Definition: io.micronaut.http.server.netty.converters.NettyConverters, Definition: io.micronaut.reactor.convert.ReactorConverterRegistrar, Definition: io.micronaut.runtime.converters.time.TimeConverterRegistrar, Definition: io.micronaut.jackson.databind.convert.JacksonConverterRegistrar, Definition: io.micronaut.json.convert.JsonConverterRegistrar, Definition: io.micronaut.http.client.loadbalance.LoadBalancerConverters, Definition: io.micronaut.runtime.converters.reactive.ReactiveTypeConverterRegistrar, Definition: io.micronaut.oraclecloud.core.OracleCloudConverterRegistrar] for type: TypeConverterRegistrar
[36m15:44:34.151[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.http.converters.HttpConverterRegistrar, Definition: io.micronaut.http.server.netty.converters.NettyConverters, Definition: io.micronaut.reactor.convert.ReactorConverterRegistrar, Definition: io.micronaut.runtime.converters.time.TimeConverterRegistrar, Definition: io.micronaut.jackson.databind.convert.JacksonConverterRegistrar, Definition: io.micronaut.json.convert.JsonConverterRegistrar, Definition: io.micronaut.http.client.loadbalance.LoadBalancerConverters, Definition: io.micronaut.runtime.converters.reactive.ReactiveTypeConverterRegistrar, Definition: io.micronaut.oraclecloud.core.OracleCloudConverterRegistrar]
[36m15:44:34.152[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: ResourceResolver resourceResolver
[36m15:44:34.153[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.resource.ResourceLoaderFactory] for type: ResourceResolver resourceResolver
[36m15:44:34.153[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.http.resource.ResourceLoaderFactory]
[36m15:44:34.153[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.http.resource.ResourceLoaderFactory] for type: resourceResolver 
[36m15:44:34.153[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: ResourceLoaderFactory
[36m15:44:34.210[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.resource.ResourceLoaderFactory] for type: ResourceLoaderFactory
[36m15:44:34.231[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.http.resource.ResourceLoaderFactory]
[36m15:44:34.232[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.http.resource.ResourceLoaderFactory] for type: ResourceLoaderFactory 
[36m15:44:34.233[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@6d3a388c] for type [Environment environment] and qualifier [null]
[36m15:44:34.233[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.http.resource.ResourceLoaderFactory@12a94400] from definition [Definition: io.micronaut.http.resource.ResourceLoaderFactory] with qualifier [null]
[36m15:44:34.233[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.http.resource.ResourceLoaderFactory@12a94400 for type [ResourceLoaderFactory] using bean key ResourceLoaderFactory
[36m15:44:34.234[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolving beans for type: io.micronaut.core.io.ResourceLoader
[36m15:44:34.234[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: ResourceLoader E
[36m15:44:34.235[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.resource.ResourceLoaderFactory, io.micronaut.context.DefaultBeanContext$NoInjectionBeanDefinition@41c2284a, Definition: io.micronaut.http.resource.ResourceLoaderFactory] for type: ResourceLoader E
[36m15:44:34.236[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.http.resource.ResourceLoaderFactory, io.micronaut.context.DefaultBeanContext$NoInjectionBeanDefinition@41c2284a, Definition: io.micronaut.http.resource.ResourceLoaderFactory]
[36m15:44:34.255[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.http.resource.ResourceLoaderFactory@12a94400] for type [ResourceLoaderFactory] and qualifier [null]
[36m15:44:34.255[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.core.io.scan.DefaultClassPathResourceLoader@11bb571c] from definition [Definition: io.micronaut.http.resource.ResourceLoaderFactory] with qualifier [null]
[36m15:44:34.255[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.core.io.scan.DefaultClassPathResourceLoader@11bb571c for type [E] using bean key ClassPathResourceLoader
[36m15:44:34.256[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.http.resource.ResourceLoaderFactory@12a94400] for type [ResourceLoaderFactory] and qualifier [null]
[36m15:44:34.258[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.core.io.file.DefaultFileSystemResourceLoader@67b9b51a] from definition [Definition: io.micronaut.http.resource.ResourceLoaderFactory] with qualifier [null]
[36m15:44:34.258[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.core.io.file.DefaultFileSystemResourceLoader@67b9b51a for type [E] using bean key FileSystemResourceLoader
[36m15:44:34.258[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found 3 beans for type [E]: [BeanRegistration: io.micronaut.core.io.scan.DefaultClassPathResourceLoader@11bb571c, BeanRegistration: io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@6d3a388c, BeanRegistration: io.micronaut.core.io.file.DefaultFileSystemResourceLoader@67b9b51a] 
[36m15:44:34.263[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.core.io.ResourceResolver@1205bd62] from definition [Definition: io.micronaut.http.resource.ResourceLoaderFactory] with qualifier [null]
[36m15:44:34.263[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.core.io.ResourceResolver@1205bd62 for type [ResourceResolver] using bean key ResourceResolver
[36m15:44:34.263[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.http.converters.HttpConverterRegistrar@7ef27d7f] from definition [Definition: io.micronaut.http.converters.HttpConverterRegistrar] with qualifier [null]
[36m15:44:34.264[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.http.converters.HttpConverterRegistrar@7ef27d7f for type [TypeConverterRegistrar] using bean key HttpConverterRegistrar
[36m15:44:34.269[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@6d3a388c for type [conversionService] using bean key RuntimeConfiguredEnvironment
[36m15:44:34.269[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@6d3a388c] for type [ConversionService conversionService] and qualifier [null]
[36m15:44:34.269[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: BeanProvider decoderRegistryProvider
[36m15:44:34.269[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: BeanProvider decoderRegistryProvider
[36m15:44:34.269[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee]
[36m15:44:34.270[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: decoderRegistryProvider 
[36m15:44:34.270[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: MediaTypeCodecRegistry T
[36m15:44:34.277[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.runtime.http.codec.MediaTypeCodecRegistryFactory] for type: MediaTypeCodecRegistry T
[36m15:44:34.277[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.runtime.http.codec.MediaTypeCodecRegistryFactory]
[36m15:44:34.277[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.inject.provider.BeanProviderDefinition$1@55cf0d14] from definition [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] with qualifier [null]
[36m15:44:34.277[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: ChannelOptionFactory channelOptionFactory
[36m15:44:34.279[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: EpollChannelOptionFactory
[36m15:44:34.280[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.http.netty.channel.converters.$EpollChannelOptionFactory$Definition] will not be loaded due to failing conditions:
[36m15:44:34.280[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [io.netty.channel.epoll.Epoll] is not present
[36m15:44:34.281[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [] for type: EpollChannelOptionFactory
[36m15:44:34.281[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: KQueueChannelOptionFactory
[36m15:44:34.282[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.http.netty.channel.converters.$KQueueChannelOptionFactory$Definition] will not be loaded due to failing conditions:
[36m15:44:34.282[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [io.netty.channel.kqueue.KQueue] is not present
[36m15:44:34.282[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [] for type: KQueueChannelOptionFactory
[36m15:44:34.282[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.http.netty.channel.converters.$EpollChannelOptionFactory$Definition] will not be loaded due to failing conditions:
[36m15:44:34.286[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [io.netty.channel.epoll.Epoll] is not present
[36m15:44:34.286[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.http.netty.channel.converters.$KQueueChannelOptionFactory$Definition] will not be loaded due to failing conditions:
[36m15:44:34.286[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [io.netty.channel.kqueue.KQueue] is not present
[36m15:44:34.287[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.http.netty.channel.converters.DefaultChannelOptionFactory] for type: ChannelOptionFactory channelOptionFactory
[36m15:44:34.287[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.http.netty.channel.converters.DefaultChannelOptionFactory]
[36m15:44:34.287[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.http.netty.channel.converters.DefaultChannelOptionFactory] for type: channelOptionFactory 
[36m15:44:34.287[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.http.netty.channel.converters.DefaultChannelOptionFactory@563e4951] from definition [Definition: io.micronaut.http.netty.channel.converters.DefaultChannelOptionFactory] with qualifier [null]
[36m15:44:34.287[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.http.netty.channel.converters.DefaultChannelOptionFactory@563e4951 for type [ChannelOptionFactory] using bean key DefaultChannelOptionFactory
[36m15:44:34.287[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.http.server.netty.converters.NettyConverters@4066c471] from definition [Definition: io.micronaut.http.server.netty.converters.NettyConverters] with qualifier [null]
[36m15:44:34.287[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.http.server.netty.converters.NettyConverters@4066c471 for type [TypeConverterRegistrar] using bean key NettyConverters
[36m15:44:34.288[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.reactor.convert.ReactorConverterRegistrar@3eb81efb] from definition [Definition: io.micronaut.reactor.convert.ReactorConverterRegistrar] with qualifier [null]
[36m15:44:34.307[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.reactor.convert.ReactorConverterRegistrar@3eb81efb for type [TypeConverterRegistrar] using bean key ReactorConverterRegistrar
[36m15:44:34.312[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.runtime.converters.time.TimeConverterRegistrar@6cdba6dc] from definition [Definition: io.micronaut.runtime.converters.time.TimeConverterRegistrar] with qualifier [null]
[36m15:44:34.312[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.runtime.converters.time.TimeConverterRegistrar@6cdba6dc for type [TypeConverterRegistrar] using bean key TimeConverterRegistrar
[36m15:44:34.372[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: BeanProvider objectMapper
[36m15:44:34.372[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: BeanProvider objectMapper
[36m15:44:34.373[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee]
[36m15:44:34.373[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: objectMapper 
[36m15:44:34.373[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: ObjectMapper T
[36m15:44:34.392[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.jackson.ObjectMapperFactory] for type: ObjectMapper T
[36m15:44:34.396[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.jackson.ObjectMapperFactory]
[36m15:44:34.396[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.inject.provider.BeanProviderDefinition$1@1f75a668] from definition [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] with qualifier [null]
[36m15:44:34.397[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@6d3a388c for type [conversionService] using bean key RuntimeConfiguredEnvironment
[36m15:44:34.397[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@6d3a388c] for type [ConversionService conversionService] and qualifier [null]
[36m15:44:34.397[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.jackson.databind.convert.JacksonConverterRegistrar@35399441] from definition [Definition: io.micronaut.jackson.databind.convert.JacksonConverterRegistrar] with qualifier [null]
[36m15:44:34.397[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.jackson.databind.convert.JacksonConverterRegistrar@35399441 for type [TypeConverterRegistrar] using bean key JacksonConverterRegistrar
[36m15:44:34.404[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: BeanProvider objectCodec
[36m15:44:34.404[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: BeanProvider objectCodec
[36m15:44:34.404[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee]
[36m15:44:34.404[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: objectCodec 
[36m15:44:34.405[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: JsonMapper T
[36m15:44:34.408[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.jackson.databind.JacksonDatabindMapper] for type: JsonMapper T
[36m15:44:34.408[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.jackson.databind.JacksonDatabindMapper]
[36m15:44:34.408[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.inject.provider.BeanProviderDefinition$1@5e403b4a] from definition [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] with qualifier [null]
[36m15:44:34.409[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@6d3a388c for type [conversionService] using bean key RuntimeConfiguredEnvironment
[36m15:44:34.409[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@6d3a388c] for type [ConversionService conversionService] and qualifier [null]
[36m15:44:34.409[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: BeanProvider beanPropertyBinder
[36m15:44:34.409[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: BeanProvider beanPropertyBinder
[36m15:44:34.409[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee]
[36m15:44:34.409[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] for type: beanPropertyBinder 
[36m15:44:34.409[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: BeanPropertyBinder T
[36m15:44:34.411[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.json.bind.JsonBeanPropertyBinder] for type: BeanPropertyBinder T
[36m15:44:34.412[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.json.bind.JsonBeanPropertyBinder]
[36m15:44:34.412[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.inject.provider.BeanProviderDefinition$1@2931522b] from definition [io.micronaut.inject.provider.BeanProviderDefinition@6e5d94ee] with qualifier [null]
[36m15:44:34.412[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.json.convert.JsonConverterRegistrar@7674b62c] from definition [Definition: io.micronaut.json.convert.JsonConverterRegistrar] with qualifier [null]
[36m15:44:34.412[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.json.convert.JsonConverterRegistrar@7674b62c for type [TypeConverterRegistrar] using bean key JsonConverterRegistrar
[36m15:44:34.412[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.http.client.loadbalance.LoadBalancerConverters@662706a7] from definition [Definition: io.micronaut.http.client.loadbalance.LoadBalancerConverters] with qualifier [null]
[36m15:44:34.412[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.http.client.loadbalance.LoadBalancerConverters@662706a7 for type [TypeConverterRegistrar] using bean key LoadBalancerConverters
[36m15:44:34.413[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.runtime.converters.reactive.ReactiveTypeConverterRegistrar@16b2bb0c] from definition [Definition: io.micronaut.runtime.converters.reactive.ReactiveTypeConverterRegistrar] with qualifier [null]
[36m15:44:34.413[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.runtime.converters.reactive.ReactiveTypeConverterRegistrar@16b2bb0c for type [TypeConverterRegistrar] using bean key ReactiveTypeConverterRegistrar
[36m15:44:34.413[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.oraclecloud.core.OracleCloudConverterRegistrar@6cb6decd] from definition [Definition: io.micronaut.oraclecloud.core.OracleCloudConverterRegistrar] with qualifier [null]
[36m15:44:34.413[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.oraclecloud.core.OracleCloudConverterRegistrar@6cb6decd for type [TypeConverterRegistrar] using bean key OracleCloudConverterRegistrar
[36m15:44:34.413[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found 9 beans for type [TypeConverterRegistrar]: [BeanRegistration: io.micronaut.http.client.loadbalance.LoadBalancerConverters@662706a7, BeanRegistration: io.micronaut.http.server.netty.converters.NettyConverters@4066c471, BeanRegistration: io.micronaut.runtime.converters.time.TimeConverterRegistrar@6cdba6dc, BeanRegistration: io.micronaut.reactor.convert.ReactorConverterRegistrar@3eb81efb, BeanRegistration: io.micronaut.json.convert.JsonConverterRegistrar@7674b62c, BeanRegistration: io.micronaut.oraclecloud.core.OracleCloudConverterRegistrar@6cb6decd, BeanRegistration: io.micronaut.jackson.databind.convert.JacksonConverterRegistrar@35399441, BeanRegistration: io.micronaut.http.converters.HttpConverterRegistrar@7ef27d7f, BeanRegistration: io.micronaut.runtime.converters.reactive.ReactiveTypeConverterRegistrar@16b2bb0c] 
[36m15:44:34.583[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.logging.$PropertiesLoggingLevelsConfigurer$Definition] will not be loaded due to failing conditions:
[36m15:44:34.583[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Required property [logger.levels] with value [null] not present
[36m15:44:34.585[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.flyway.FlywayConfigurationProperties]
[36m15:44:35.033[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: DataSource
[36m15:44:35.034[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceFactory] for type: DataSource
[36m15:44:35.035[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: DatasourceConfiguration
[36m15:44:35.048[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration] for type: DatasourceConfiguration
[36m15:44:35.050[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration]
[36m15:44:35.051[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceFactory]
[36m15:44:35.051[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.flyway.FlywayConfigurationProperties@676cf48] from definition [Definition: io.micronaut.flyway.FlywayConfigurationProperties] with qualifier [@Named('default')]
[36m15:44:35.052[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.flyway.FlywayConfigurationProperties@676cf48 for type [@Named('default') FlywayConfigurationProperties] using bean key @Named('default') FlywayConfigurationProperties
[36m15:44:35.053[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolving beans for type: io.micronaut.data.jdbc.config.DataJdbcConfiguration
[36m15:44:35.053[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: DataJdbcConfiguration E
[36m15:44:35.065[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.data.jdbc.config.DataJdbcConfiguration] for type: DataJdbcConfiguration E
[36m15:44:35.066[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.data.jdbc.config.DataJdbcConfiguration]
[36m15:44:35.067[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.config.DataJdbcConfiguration@4ed5eb72] from definition [Definition: io.micronaut.data.jdbc.config.DataJdbcConfiguration] with qualifier [@Named('default')]
[36m15:44:35.068[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.data.jdbc.config.DataJdbcConfiguration@4ed5eb72 for type [@Named('default') E] using bean key @Named('default') DataJdbcConfiguration
[36m15:44:35.068[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found 1 beans for type [E]: [BeanRegistration: io.micronaut.data.jdbc.config.DataJdbcConfiguration@4ed5eb72] 
[36m15:44:35.069[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: RuntimeEntityRegistry
[36m15:44:35.072[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.data.runtime.support.DefaultRuntimeEntityRegistry] for type: RuntimeEntityRegistry
[36m15:44:35.079[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.data.runtime.support.DefaultRuntimeEntityRegistry]
[36m15:44:35.079[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.data.runtime.support.DefaultRuntimeEntityRegistry] for type: RuntimeEntityRegistry 
[36m15:44:35.090[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: EntityEventRegistry eventRegistry
[36m15:44:35.092[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.data.runtime.event.EntityEventRegistry] for type: EntityEventRegistry eventRegistry
[36m15:44:35.157[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.data.runtime.event.EntityEventRegistry]
[36m15:44:35.216[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.data.runtime.event.EntityEventRegistry] for type: eventRegistry 
[36m15:44:35.220[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: EntityEventListener
[36m15:44:35.225[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.data.runtime.event.listeners.VersionGeneratingEntityEventListener, Definition: io.micronaut.data.runtime.event.listeners.AnnotatedMethodInvokingEntityEventListener, Definition: io.micronaut.data.runtime.event.listeners.AutoTimestampEntityEventListener, Definition: io.micronaut.data.runtime.event.EntityEventRegistry, Definition: io.micronaut.data.runtime.event.listeners.UUIDGeneratingEntityEventListener] for type: EntityEventListener
[36m15:44:35.225[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.data.runtime.event.listeners.VersionGeneratingEntityEventListener, Definition: io.micronaut.data.runtime.event.listeners.AnnotatedMethodInvokingEntityEventListener, Definition: io.micronaut.data.runtime.event.listeners.AutoTimestampEntityEventListener, Definition: io.micronaut.data.runtime.event.EntityEventRegistry, Definition: io.micronaut.data.runtime.event.listeners.UUIDGeneratingEntityEventListener]
[36m15:44:35.227[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for qualifier: @EntityEventMapping
[36m15:44:35.236[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.runtime.event.EntityEventRegistry@2dcd168a] from definition [Definition: io.micronaut.data.runtime.event.EntityEventRegistry] with qualifier [null]
[36m15:44:35.247[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.data.runtime.event.EntityEventRegistry@2dcd168a for type [EntityEventRegistry] using bean key EntityEventRegistry
[36m15:44:35.264[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolving beans for type: io.micronaut.data.model.runtime.PropertyAutoPopulator<java.lang.annotation.Annotation>
[36m15:44:35.268[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: PropertyAutoPopulator T
[36m15:44:35.317[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.data.runtime.event.listeners.VersionGeneratingEntityEventListener, Definition: io.micronaut.data.runtime.event.listeners.AutoTimestampEntityEventListener] for type: PropertyAutoPopulator T
[36m15:44:35.361[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.data.runtime.event.listeners.VersionGeneratingEntityEventListener, Definition: io.micronaut.data.runtime.event.listeners.AutoTimestampEntityEventListener]
[36m15:44:35.362[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: DateTimeProvider dateTimeProvider
[36m15:44:35.369[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.data.runtime.date.CurrentDateTimeProvider] for type: DateTimeProvider dateTimeProvider
[36m15:44:35.369[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.data.runtime.date.CurrentDateTimeProvider]
[36m15:44:35.370[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.data.runtime.date.CurrentDateTimeProvider] for type: dateTimeProvider 
[36m15:44:35.370[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.runtime.date.CurrentDateTimeProvider@62ef27a8] from definition [Definition: io.micronaut.data.runtime.date.CurrentDateTimeProvider] with qualifier [null]
[36m15:44:35.370[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.data.runtime.date.CurrentDateTimeProvider@62ef27a8 for type [DateTimeProvider] using bean key CurrentDateTimeProvider
[36m15:44:35.371[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: DataConversionService conversionService
[36m15:44:35.384[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.data.runtime.convert.DataConversionServiceFactory] for type: DataConversionService conversionService
[36m15:44:35.386[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.data.runtime.convert.DataConversionServiceFactory]
[36m15:44:35.386[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.data.runtime.convert.DataConversionServiceFactory] for type: conversionService 
[36m15:44:35.387[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: DataConversionServiceFactory
[36m15:44:35.391[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.data.runtime.convert.DataConversionServiceFactory] for type: DataConversionServiceFactory
[36m15:44:35.391[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.data.runtime.convert.DataConversionServiceFactory]
[36m15:44:35.391[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.data.runtime.convert.DataConversionServiceFactory] for type: DataConversionServiceFactory 
[36m15:44:35.392[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.runtime.convert.DataConversionServiceFactory@25aca718] from definition [Definition: io.micronaut.data.runtime.convert.DataConversionServiceFactory] with qualifier [null]
[36m15:44:35.397[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.data.runtime.convert.DataConversionServiceFactory@25aca718 for type [DataConversionServiceFactory] using bean key DataConversionServiceFactory
[36m15:44:35.519[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolving beans for type: io.micronaut.data.runtime.convert.DataTypeConverter
[36m15:44:35.519[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: DataTypeConverter
[36m15:44:35.521[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] for type: DataTypeConverter
[36m15:44:35.522[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory, Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory]
[36m15:44:35.522[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory@6e01f9b0] for type [OracleTypeConvertersFactory] and qualifier [null]
[36m15:44:35.522[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$278/0x0000000840845840@421e361] from definition [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] with qualifier [null]
[36m15:44:35.522[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory@6e01f9b0] for type [OracleTypeConvertersFactory] and qualifier [null]
[36m15:44:35.522[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$279/0x0000000840845c40@389c4eb1] from definition [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] with qualifier [null]
[36m15:44:35.522[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory@6e01f9b0] for type [OracleTypeConvertersFactory] and qualifier [null]
[36m15:44:35.522[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$280/0x0000000840846040@1187c9e8] from definition [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] with qualifier [null]
[36m15:44:35.523[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory@6e01f9b0] for type [OracleTypeConvertersFactory] and qualifier [null]
[36m15:44:35.523[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$281/0x0000000840846440@78a773fd] from definition [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] with qualifier [null]
[36m15:44:35.523[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory@6e01f9b0] for type [OracleTypeConvertersFactory] and qualifier [null]
[36m15:44:35.523[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$282/0x0000000840846840@16aa8654] from definition [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] with qualifier [null]
[36m15:44:35.523[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory@6e01f9b0] for type [OracleTypeConvertersFactory] and qualifier [null]
[36m15:44:35.523[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$283/0x0000000840846c40@45ac5f9b] from definition [Definition: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory] with qualifier [null]
[36m15:44:35.523[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found 6 beans for type [DataTypeConverter]: [BeanRegistration: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$281/0x0000000840846440@78a773fd, BeanRegistration: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$280/0x0000000840846040@1187c9e8, BeanRegistration: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$282/0x0000000840846840@16aa8654, BeanRegistration: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$283/0x0000000840846c40@45ac5f9b, BeanRegistration: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$278/0x0000000840845840@421e361, BeanRegistration: io.micronaut.data.jdbc.convert.vendor.OracleTypeConvertersFactory$$Lambda$279/0x0000000840845c40@389c4eb1] 
[36m15:44:35.523[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolving beans for type: io.micronaut.core.convert.TypeConverterRegistrar
[36m15:44:35.525[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.runtime.convert.DataConversionServiceImpl@38831718] from definition [Definition: io.micronaut.data.runtime.convert.DataConversionServiceFactory] with qualifier [null]
[36m15:44:35.525[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.data.runtime.convert.DataConversionServiceImpl@38831718 for type [io.micronaut.data.runtime.convert.DataConversionService] using bean key DataConversionService
[36m15:44:35.525[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.runtime.event.listeners.VersionGeneratingEntityEventListener@2c1156a7] from definition [Definition: io.micronaut.data.runtime.event.listeners.VersionGeneratingEntityEventListener] with qualifier [null]
[36m15:44:35.525[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.data.runtime.event.listeners.VersionGeneratingEntityEventListener@2c1156a7 for type [T] using bean key VersionGeneratingEntityEventListener
[36m15:44:35.526[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.data.runtime.date.CurrentDateTimeProvider@62ef27a8 for type [dateTimeProvider] using bean key CurrentDateTimeProvider
[36m15:44:35.526[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.data.runtime.date.CurrentDateTimeProvider@62ef27a8] for type [DateTimeProvider dateTimeProvider] and qualifier [null]
[36m15:44:35.527[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.data.runtime.convert.DataConversionServiceImpl@38831718 for type [io.micronaut.data.runtime.convert.DataConversionService] using bean key DataConversionService
[36m15:44:35.527[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved existing bean [io.micronaut.data.runtime.convert.DataConversionServiceImpl@38831718] for type [DataConversionService conversionService] and qualifier [null]
[36m15:44:35.527[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.runtime.event.listeners.AutoTimestampEntityEventListener@691939c9] from definition [Definition: io.micronaut.data.runtime.event.listeners.AutoTimestampEntityEventListener] with qualifier [null]
[36m15:44:35.527[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.data.runtime.event.listeners.AutoTimestampEntityEventListener@691939c9 for type [T] using bean key AutoTimestampEntityEventListener
[36m15:44:35.527[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found 2 beans for type [T]: [BeanRegistration: io.micronaut.data.runtime.event.listeners.VersionGeneratingEntityEventListener@2c1156a7, BeanRegistration: io.micronaut.data.runtime.event.listeners.AutoTimestampEntityEventListener@691939c9] 
[36m15:44:35.556[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: AttributeConverterRegistry attributeConverterRegistry
[36m15:44:35.572[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.data.runtime.support.convert.DefaultAttributeConverterRegistry] for type: AttributeConverterRegistry attributeConverterRegistry
[36m15:44:35.574[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.data.runtime.support.convert.DefaultAttributeConverterRegistry]
[36m15:44:35.575[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.data.runtime.support.convert.DefaultAttributeConverterRegistry] for type: attributeConverterRegistry 
[36m15:44:35.576[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolving beans for type: io.micronaut.data.runtime.support.convert.AttributeConverterProvider
[36m15:44:35.577[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: AttributeConverterProvider E
[36m15:44:35.581[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.data.runtime.support.convert.convert.jpa.$JxAttributeConverterProvider$Definition] will not be loaded due to failing conditions:
[36m15:44:35.583[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [javax.persistence.AttributeConverter] is not present
[36m15:44:35.584[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - Bean [io.micronaut.data.runtime.support.convert.convert.jpa.$JakartaAttributeConverterProvider$Definition] will not be loaded due to failing conditions:
[36m15:44:35.585[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.condition.Condition[0;39m - * Class [jakarta.persistence.AttributeConverter] is not present
[36m15:44:35.586[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [] for type: AttributeConverterProvider E
[36m15:44:35.611[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found no possible candidate beans of type [E] for qualifier: null 
[36m15:44:35.612[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.runtime.support.convert.DefaultAttributeConverterRegistry@61a88b8c] from definition [Definition: io.micronaut.data.runtime.support.convert.DefaultAttributeConverterRegistry] with qualifier [null]
[36m15:44:35.612[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.data.runtime.support.convert.DefaultAttributeConverterRegistry@61a88b8c for type [AttributeConverterRegistry] using bean key DefaultAttributeConverterRegistry
[36m15:44:35.626[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.runtime.support.DefaultRuntimeEntityRegistry@3f270e0a] from definition [Definition: io.micronaut.data.runtime.support.DefaultRuntimeEntityRegistry] with qualifier [null]
[36m15:44:35.626[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.data.runtime.support.DefaultRuntimeEntityRegistry@3f270e0a for type [RuntimeEntityRegistry] using bean key DefaultRuntimeEntityRegistry
[36m15:44:35.626[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.data.jdbc.config.SchemaGenerator@1a760689] from definition [Definition: io.micronaut.data.jdbc.config.SchemaGenerator] with qualifier [null]
[36m15:44:35.626[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.data.jdbc.config.SchemaGenerator@1a760689 for type [SchemaGenerator] using bean key SchemaGenerator
[36m15:44:35.626[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.oraclecloud.atp.jdbc.AutonomousDatabaseConfiguration]
[36m15:44:35.629[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.oraclecloud.atp.jdbc.AutonomousDatabaseConfiguration@331acdad] from definition [Definition: io.micronaut.oraclecloud.atp.jdbc.AutonomousDatabaseConfiguration] with qualifier [@Named('default')]
[36m15:44:35.629[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.oraclecloud.atp.jdbc.AutonomousDatabaseConfiguration@331acdad for type [@Named('default') AutonomousDatabaseConfiguration] using bean key @Named('default') AutonomousDatabaseConfiguration
[36m15:44:35.629[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: DatasourceConfiguration
[36m15:44:35.632[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration] for type: DatasourceConfiguration
[36m15:44:35.632[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration]
[36m15:44:35.633[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceFactory]
[36m15:44:35.633[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: DatasourceFactory
[36m15:44:35.647[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceFactory] for type: DatasourceFactory
[36m15:44:35.647[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceFactory]
[36m15:44:35.647[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceFactory] for type: DatasourceFactory 
[36m15:44:35.648[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.context.lifecycle[0;39m - Created bean [io.micronaut.configuration.jdbc.hikari.DatasourceFactory@f316aeb] from definition [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceFactory] with qualifier [null]
[36m15:44:35.649[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Registering singleton bean io.micronaut.configuration.jdbc.hikari.DatasourceFactory@f316aeb for type [DatasourceFactory] using bean key DatasourceFactory
[36m15:44:35.650[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finding candidate beans for type: DatasourceConfiguration datasourceConfiguration
[36m15:44:35.652[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Resolved bean candidates [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration] for type: DatasourceConfiguration datasourceConfiguration
[36m15:44:35.652[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Finalized bean definitions candidates: [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration]
[36m15:44:35.652[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Qualifying bean [datasourceConfiguration] for qualifier: @Named('default') 
[36m15:44:35.652[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mi.m.context.DefaultBeanContext[0;39m - Found concrete candidate [Definition: io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration] for type: @Named('default') datasourceConfiguration 
[36m15:44:35.664[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.core.reflect.ClassUtils[0;39m - Attempting to dynamically load class org.h2.Driver
[36m15:44:35.665[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.core.reflect.ClassUtils[0;39m - Class org.h2.Driver is not present
[36m15:44:35.665[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.core.reflect.ClassUtils[0;39m - Attempting to dynamically load class org.apache.derby.jdbc.EmbeddedDriver
[36m15:44:35.665[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.core.reflect.ClassUtils[0;39m - Class org.apache.derby.jdbc.EmbeddedDriver is not present
[36m15:44:35.665[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.core.reflect.ClassUtils[0;39m - Attempting to dynamically load class org.hsqldb.jdbc.JDBCDriver
[36m15:44:35.666[0;39m [1;30m[main][0;39m [39mDEBUG[0;39m [35mio.micronaut.core.reflect.ClassUtils[0;39m - Class org.hsqldb.jdbc.JDBCDriver is not present
[36m15:44:35.719[0;39m [1;30m[main][0;39m [1;31mERROR[0;39m [35mio.micronaut.runtime.Micronaut[0;39m - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]

Message: Error configuring data source 'default'. No URL specified
Path Taken: DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]

Message: Error configuring data source 'default'. No URL specified
Path Taken: DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1938)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:237)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3453)
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3883)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:329)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:183)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:313)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at my.app.Application.main(Application.java:8)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [javax.sql.DataSource]

Message: Error configuring data source 'default'. No URL specified
Path Taken: DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2363)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2820)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2782)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1638)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1933)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1189)
	at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0$Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:136)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2653)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1932)
	... 9 common frames omitted
Caused by: io.micronaut.context.exceptions.ConfigurationException: Error configuring data source 'default'. No URL specified
	at io.micronaut.jdbc.CalculatedSettings.getUrl(CalculatedSettings.java:109)
	at io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration.getUrl(DatasourceConfiguration.java:96)
	at io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration.postConstruct(DatasourceConfiguration.java:68)
	at io.micronaut.configuration.jdbc.hikari.$DatasourceConfiguration$Definition.initialize(Unknown Source)
	at io.micronaut.configuration.jdbc.hikari.$DatasourceConfiguration$Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinition.build(AbstractInitializableBeanDefinition.java:707)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:132)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
	... 23 common frames omitted

> Task :run FAILED
3 actionable tasks: 2 executed, 1 up-to-date
```

### Steps To Reproduce

1. Follow a guide from https://guides.micronaut.io/latest/micronaut-oracle-autonomous-db-gradle-java.html without installing Oracle Cloud CLI 
2. Create application-oraclecloud.yml
```
datasources:
  default:
    ocid: your ocid
    walletPassword: pass
    username: yourusername
    password: yourpassword
oci:
  config:
  profile: DEFAULT
```
3. Try to start an application

### Environment Information

_No response_

### Example Application

_No response_

### Version

v3.2.4

### PR DESCRIPTION
**Pull request by pgressa**
!Fixes #322

### CODE REVIEW

File: oraclecloud-atp/src/main/java/io/micronaut/oraclecloud/atp/jdbc/hikari/HikariPoolConfigurationListener.java [hunk 1]
```diff
@@ -61,7 +65,8 @@
      * @param walletArchiveProvider The wallet archive provider
      * @param beanLocator           The bean locator
      */
-    protected HikariPoolConfigurationListener(OracleWalletArchiveProvider walletArchiveProvider, BeanLocator beanLocator) {
+    protected HikariPoolConfigurationListener(@Nullable OracleWalletArchiveProvider walletArchiveProvider,
```
Comment (pgressa) [inline oraclecloud-atp/src/main/java/io/micronaut/oraclecloud/atp/jdbc/hikari/HikariPoolConfigurationListener.java:68]: @graemerocher could adding validation annotation be considered as an  breaking change?

File: oraclecloud-atp/src/main/java/io/micronaut/oraclecloud/atp/jdbc/hikari/HikariPoolConfigurationListener.java [hunk 2]
```diff
@@ -85,6 +90,12 @@ public DatasourceConfiguration onInitialized(BeanInitializingEvent<DatasourceCon
             LOG.trace("Skipping configuration of Oracle Wallet due to missin ocid or wallet password in " +
                     "AutonomousDatabaseConfiguration for [{}] datasource", beanName);
         } else {
+
+            if (walletArchiveProvider == null && !beanLocator.findBean(AbstractAuthenticationDetailsProvider.class).isPresent()) {
```
Comment (graemerocher) [inline oraclecloud-atp/src/main/java/io/micronaut/oraclecloud/atp/jdbc/hikari/HikariPoolConfigurationListener.java:94]: You can use `!containsBean` here instead

File: oraclecloud-atp/src/main/java/io/micronaut/oraclecloud/atp/jdbc/upc/UcpPoolConfigurationListener.java [hunk 3]
```diff
@@ -93,6 +97,12 @@ public DataSource onCreated(BeanCreatedEvent<DataSource> event) {
                 LOG.trace("Skipping configuration of Oracle Wallet due to missing ocid or wallet password in " +
                         "AutonomousDatabaseConfiguration for [{}] datasource", beanName);
             } else {
+
+                if (walletArchiveProvider == null && !beanLocator.findBean(AbstractAuthenticationDetailsProvider.class).isPresent()) {
```
Comment (graemerocher) [inline oraclecloud-atp/src/main/java/io/micronaut/oraclecloud/atp/jdbc/upc/UcpPoolConfigurationListener.java:101]: Same here

**Review by graemerocher — CHANGES_REQUESTED** [review]

File: oraclecloud-atp/src/main/java/io/micronaut/oraclecloud/atp/jdbc/hikari/HikariPoolConfigurationListener.java (hunk 2 above)
Comment (pgressa) [reply oraclecloud-atp/src/main/java/io/micronaut/oraclecloud/atp/jdbc/hikari/HikariPoolConfigurationListener.java:94]: @graemerocher https://docs.micronaut.io/3.2.6/api/io/micronaut/context/BeanLocator.html no containsBean.. it's not bean context
